### ISSUE TITLE
[Feature] The application is unable to cache the login session and user has to login every time after restarting the app

### ISSUE THREAD

**Issue by minhnimble** [thienhm17/Nimble-Code-Chanllenge#4]
## Why

Currently, I noticed that once logged in successfully, terminating the application will ask the user to login again every time even though there is implemented logic to store the tokens already. This is actually a part of the requirement to keep the user logged in after the first successful authentication.

## Expectation

- Implement the OAuth authentication including the storage of access tokens to keep the user logged in.

## Actual

- The user has to login again every time restarting the application:

https://user-images.githubusercontent.com/70877098/161488202-987d64dd-9a8f-4152-9592-13bb7c17e357.mp4

**Comment by thienhm17** [comment]
I will update it
