### ISSUE TITLE
[Bug] [UI] Contents on the Surveys List screen are difficult to see

### ISSUE THREAD

**Issue by minhnimble** [thienhm17/Nimble-Code-Chanllenge#9]
## Why

The application needs to show the survey list screen after loading all the data with a valid logged in session like design. Currently there are a few problems with the survey list screen:
- The status bar color is shown in black instead of white like design.
- The date label's text is being localized unnecessarily depending on the phone's localization and it causes content inconsistent issues. Do you think it is worth updating the text here to English?
- In brighter background images, we would not be able to see the text clearly as texts are in white. What do you think about adding some dark overlay over the image in order to make text more legible?
- The display image for each survey item is very blurry. Can we update to use the high-quality version for the images?

## Expectation
- The survey list screen needs to be easy to see like the following design:

<img src="https://user-images.githubusercontent.com/70877098/159682538-5934d10f-fd97-4c01-b95a-28b0c6199ed8.png" width="300">

## Actual:

- Date label is shown in Vietnamese and blurry survey image background:
<img src="https://user-images.githubusercontent.com/70877098/161493721-b9cb60f1-cf11-4678-8306-19e93e9117ff.png" width="300">

- White `Today` text on light background:
<img src="https://user-images.githubusercontent.com/70877098/161493847-37ee5098-7383-4dc0-8082-9ce76cef1c38.png" width="300">

- Status bar color is not viewable for dark background: 
<img src="https://user-images.githubusercontent.com/70877098/161493729-63e6aa09-1cae-4ebe-8129-549f4e2c90b6.png" width="300">

**Comment by thienhm17** [comment]
> The status bar color is shown in black instead of white like design.

> The date label's text is being localized unnecessarily depending on the phone's localization and it causes content inconsistent issues. Do you think it is worth updating the text here to English?

Yes, I will fix them

> In brighter background images, we would not be able to see the text clearly as texts are in white. What do you think about adding some dark overlay over the image in order to make text more legible?

Actually, I have added a dark gradient overlay as the mockup design. But yes, it seems not to work with some background, so I will also fix it.

> The display image for each survey item is very blurry. Can we update to use the high-quality version for the images?

Yes, I've noticed this. But I did not find any other version of the images in the API response.

**Comment by minhnimble** [comment]
> Actually, I have added a dark gradient overlay as the mockup design. But yes, it seems not to work with some background, so I will also fix it.
→ Oh I don't realize that you have included the dark layer. It seems finding the right ratio for the dark gradient overlay is quite tricky. Is there any better way you can think of to solve this issue? 🤔

> Yes, I've noticed this. But I did not find any other version of the images in the API response.

→ Maybe you have missed it but from this [Postman document](https://documenter.getpostman.com/view/11835486/UVsPNPfU#064357a5-4625-4ef7-b042-0d1f7e2f2acb) for the Survey list API, it has the mention that you can get the high-resolution of an image just append “l” to the image URL obtained in the API response. 🙂
